# This is a basic workflow to help you get started with Actions

name: npm-install

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      #
      # - name: add ssh script
      #   run: |
      #     echo Hello, world!
      #   # check ssh or install ssh
      #     command -v ssh-agent >/dev/null || (apt-get update -y && apt-get install openssh-client -y)
      #     eval $(ssh-agent -s)
      #     echo $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
      #     mkdir -p ~/.ssh && chmod 700 ~./.ssh
      #     echo $SSH_KNOW_HOSTS >> ~./.ssh/known_hosts && chmod 644 ~./.ssh/known_hosts
      #     ssh root@host

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install